## Habitat Zonation


Throughout this report, the terms “habitat” and “ecosystem” are used synonymously to describe a generally homogeneous classification of an integrated biotic, abiotic, and social system occurring in a given area. Six different ecosystem types are included in NYBEM, and this section describes how these conceptual ecosystems were numerically delineated. The generalized criteria for delineating ecosystems (Table 3.2) were reframed as a suite of logic statements for identifying the salinity zone, tidal zone, or ecosystem type / habitat zone for any given patch. 

Tidal zone ($Z_{tidal}$) is defined as a categorical metric of deep (1), subtidal (2), intertidal (3), and upland (4) classes.

$$Z_{tidal} = \begin{pmatrix} deep(1) & elev_{bed} < -2m\\
subtidal(2) & -2<elev_{bed}<MLLW\\
intertidal(3) & MLLW<elev_{bed}<MHHW\\
upland(4) & MHHW<elev_{bed}
\end{pmatrix}$$ 

Where $elev_{bed}$ is bed elevation, $MLLW$ is mean lower low water, $MHHW$ is mean higher high water, and all elevations are presented relative to mean tide level.


Salinity zone ($Z_{salinity}$) is defined as a categorical metric of marine (1), estuarine (2), and fresh (3) classes.

$$Z_{salinity} = \begin{pmatrix} marine(1) & sal_{10}>28psu\\
estuarine(2) & 28psu>sal_{10}>0.5psu\\
fresh(3) & sal_{10}<0.5psu
\end{pmatrix}$$ 

Where $sal_{10}$ is a representative low salinity (e.g., average annual low flow, 10th percentile) in practical salinity units (psus).


Habitat zones ($Z_{habitat}$) may then be defined from logical combinations of tidal and salinity zones.

$$Z_{habitat} = \begin{pmatrix} upland(1) & Z_{tidal}=4\\
mar.deep(2) & Z_{salinity}=1,Z_{tidal}=1\\
mar.sub(3) & Z_{salinity}=1,Z_{tidal}=2\\
mar.int(4) & Z_{salinity}=1,Z_{tidal}=3\\
est.sub(5) & Z_{salinity}=2,Z_{tidal}=or(1,2)\\
est.int(6) & Z_{salinity}=2,Z_{tidal}=3\\
fresh.tid(7) & Z_{salinity}=3,Z_{tidal}=or(1,2,3)
\end{pmatrix}$$ 

Where $upland$ represents upland areas outside of the model domain, $mar.deep$ represents marine, deepwater zones, $mar.sub$ represents marine, subtidal zones, $mar.int$ represents marine, intertidal zones, $est.sub$ represents estuarine, subtidal zones, $est.int$ represents estuarine, intertidal zones, and $fresh.tid$ represents freshwater, tidal zones.

