## Marine, Deepwater Submodel (mar.deep) (I)

<span style="color: red;">Hall and McKay to write.</span>

Marine deepwater ecosystem considers areas with salinity values greater or equal to 30 ppt and depths between 2 – 20 m. Physical, biological and chemical variables effect may be compounded by anthropogenic and climatic pressures to develop an ecosystem that deviates from the baseline condition, reducing the habitat suitability of the system for multiple dependents.  

The following variables are available to assess the marine deepwater submodel portion of the NYBEM: water temperature, salinity, wave environment, suspended solids, velocity and currents, and vessel traffic. Water temperature and salinity act as proxies for vertical mixing of the water column, dissolved oxygen availability, and productivity of algal, pelagic, demersal and benthic systems. The wave environment and current velocities represent mixing and flushing of the system, sediment suspension and benthic scouring. Light penetration depths within the water column indicate water column turbidity, nutrient loading and chlorophyll-a production levels, another productivity control. Finally, vessel traffic provides an index for development pressures, both commercial and recreational fishing pressure on the pelagic, demersal and benthic systems, as well as commercial and recreational vessel density pressures on the marine mammal populations within the area (population stress from ship strikes and noise pollution).    


**FIGURE**


Describe the main ideas being captured in the model. Summarize as table. Present suitability index curves, which are described in subsequent sections.

**TABLE**

**FIGURE WITH SUITABILITY CURVES**

Present the overarching habitat suitability index equation.

**EQUATION**

Salinity and dissolved oxygen are two primary indicators of water quality and ecosystem function, condition and resilience [@smit_assessing_2021].

### Salinity

Salinity, often used as a proxy for the total concentration of all dissolved salts in the water, is a key factor in water density that controls the vertical mixing of nutrients and chemicals throughout the water column. Salinity constrains dissolved oxygen concentration and limits speciation of marine zones to euryhaline taxa that are physiological adapted to tolerate hypoosmotic processes (are able to maintain a lower internal ionic concentration than seawater).  
Depth-averaged salinity (mean, 0-100 % exceeded by 10 %), sourced from AdH summary statistics (bottom and surface salinity may be available for HATS in future analyses), are assessed within the NYBEM. 

Present the equation for assessing the suitability index.

**EQUATION**

### Dissolved Oxygen Processes

Dissolved oxygen concentration, a key element for the survival of marine species, limits speciation of marine zones through hypoxia, where low oxygen levels may cause die-offs in marine species. Dissolved oxygen concentrations act as a proxy for pelagic, demersal and benthic fauna biomass (abundance/diversity of phytoplankton, zooplankton, fish, marine turtles, birds and mammals) that indicate the productivity of the zone permanent monitoring stations, as supported by NYC DEP Monitoring Stations (2018), Jamaica Bay Eutrophication Model [@fischbach_building_2018], Chesapeake Bay model [@cerco_threedimensional_1993] and the EPA Long Island Sound integrated model (underway), are assessed within the NYBEM.

Present the equation for assessing the suitability index.

**EQUATION**

Water temperature, the wave environment, current velocity, light, depth, substrate, suspended solids, and nutrient loading. Depth is not specifically modeled within the NYBEM, but is inherent within model input variables, such as the AdH hydrodynamic model. 

### Water Temperature

Water temperature acts as a control for the majority of the chemical (dissolved nutrients, pH, density, and photosynthesis), biological (respiration and metabolic rates, taxa development, and migrations) and physical (ice formation and thermal stratification of the water column) properties of a marine ecosystem.   
MARACOOS Monthly Sea Surface Temperature from the MARCO Mid-Atlantic Ocean Data Portal and seasonal temperature thresholds for winter flounder, as identified in changes in temperature regimes that are based on AdH model outputs, are assessed within the NYBEM. The AdH model outputs are supported by the Winter flounder habitat suitability model [@banner_usfws_2001] and VIMS 2018 habitat suitability models and the USACE Harbor monitoring (USACE 2013).

Present the equation for assessing the suitability index.

**EQUATION**

### Wave Environment

The wave environment affects many variables with the NYB: vertical and horizontal mixing and flushing of the physical and chemical properties of the water, suspended sediment and solids, substrate settlement of taxa, and commercial and recreational vessel traffic.   
Wave height and wave refraction from STWAVE are assessed within the NYBEM, as supported by (@byrnes_effects_2004).

Present the equation for assessing the suitability index.

**EQUATION**

### Current Velocity

The marine deepwater environment is subjected to velocity effects from ocean currents and tides that affect vertical and horizontal mixing and flushing of the system, suspended sediment and solids, substrate settlement of taxa, and small and recreational vessel traffic. Low flow conditions allow for the settlement of sediment, possibly burying viable habitat, reduce mixing and flushing, and potentially facilitate hypoxic conditions. Conversely, high velocities scour the benthic environment, prohibiting settling in the substrate by benthic taxa.

Change in velocity, particularly in low flow conditions when flushing is of concern (i.e., 0 – 100 % exceedance by 10 %) are assessed within the NYBEM via mean and exceedance by 10 % velocity (depth-averaged), as sourced from AdH summary statistics. A recent EWN workshop supports these AdH hydrodynamic summary statistics as a proxy for velocity. 

Present the equation for assessing the suitability index.

**EQUATION**

### Derived Metrics- Light

The depth that light reaches within the water column acts as a proxy for the viability of water column turbidity, nutrient loading and chlorophyll-a production, the essential building block for ocean productivity. 

As light controls chlorophyll-a production, it may be seen as a limiting factor for algal and particulate organic matter (POM) densities, and ultimately the development of harmful algal blooms (HAB), and therefore used as a variable that represents the biological environment within the NYBEM.
Within the NYBEM, percentages of light through the Water (PLW) are derived from AdH depth outputs and empirical data on Secchi depth following methods of Kemp et al. (2004).

Present the equation for assessing the suitability index.

**EQUATION**

### Vessel Traffic and Development Pressures

Vessel traffic density provides an index for development pressures, both commercial and recreational fishing pressure on the pelagic, demersal and benthic systems, as well as commercial and recreational vessel density pressures on the marine mammal populations within the area (population stress from ship strikes and noise pollution).    

Vessel use density from the historical Automatic Identification System (AIS) vessel data from the MARCOS portal are assessed within the NYBEM to identify the general use of waterways. These data also indicate frequently visited fishing locations and offshore structures.  

Present the equation for assessing the suitability index.

**EQUATION**

### mar.deep Code

Numerical code for assessing habitat quality (<span style="color: red;">Dougherty and McKay to write.</span>)


```{r echo=TRUE}
#Function for assessing habitat quality
mar.deep <- function(x, y){
  mar.deep.HSI <- x + y

  #Send output
  mar.deep.HSI
}
```
