#  Application and Communication


The NYBEM has been explicitly designed to inform site screening and environmental impact assessment for the NJBB and HATS. A key component of this process is understanding the existing condition without project effects. This section presents a preliminary application of the NYBEM to assess ecosystem condition in the New Jersey Back Bays following four main activities:  

- Incorporation of hydrodynamic model outcomes,  
- Compilation of other environmental input data sets for the NYBEM in this region,  
- Execution of the models, and  
- Summary of model outcomes.

## NJBB Hydrodynamic Modeling


Adaptive Hydraulics (AdH) is the numerical model code applied for hydrodynamic simulations in this study. For this study, the two-dimensional (2D) shallow water module of AdH is applied for all simulations. This code solves for depth-averaged velocity and salinity throughout the model domain. (More details of the 2D shallow water module of AdH and its computational philosophy and equations are available in Savant et al. 2014 and Savant and Berger 2015.) AdH version 4.6 was applied for this study.

A 2D AdH model was developed and validated for simulation of hydrodynamics and salinity (Details provided in McAlpin and Ross, _draft_). The model was validated to available field data for all parameters and then utilized to test project alternatives for present and future sea level rise conditions. A field data collection effort was performed in February 2019 to collect salinity and discharge/velocity data over a 13-hour tidal cycle at three major inlets – Barnegat, Little Egg, and Great Egg. Field data supported the use of a 2D model as opposed to a three-dimensional (3D) model due to lack of major salinity stratification.

The model domain was determined using aerial images and bathymetry/topographic data for the area. The Surface Water Modeling System was used to generate a 2D surface mesh and define material regions for applying specific model features, such as bed roughness. The domain is defined horizontally in Universal Transverse Mercator, zone 18 coordinates with units of meters. Vertically it is based on North American Vertical Datum of 1988 (NAVD88) with units of meters. All data applied to the model are shifted to this datum and coordinate system. Bathymetry data for the model were obtained from several sources: the Coastal Relief Model, sponsor collected hydrographic surveys, and the National Elevation Dataset. These data sets were combined such that the latest data were made a priority as well as data collected at finer resolution. The 2D AdH code can include areas that wet/dry; therefore, elevations were included in the domain up to 2 m NAVD88.

The model domain includes over 9,867 square miles, extending approximately 115 miles along the New Jersey Atlantic Ocean coastline from Lewes, DE, to Manasquan, NJ. The 2D mesh contains 324,881 elements and 165,514 nodes. Figure 6.1 shows horizontal node resolution for the model with an example region surrounding the Barnegat Bay Inlet. Resolution is finest in the small wetland channels to accurately capture the conveyance of flow in these areas as well as the salinity that migrates upstream in deeper channels. Finer resolution is also seen in areas where geometric features need to be defined accurately, such as in the inlets and around jetties. 

<span style="color: red;">INSERT FIGURE 6.1</span>

Ten AdH simulations were executed: seven project alternatives and three projects rerun with sea level change. An elevation shift of 0.445 m was added to the water surface elevation at the tide boundary for sea level rise simulations to reflect the "intermediate" sea level rise curve in the year 2080 (per EC 1165-2-212). The mesh domain was not expanded to account for potential wetted area with rising sea level. Additionally, vegetated areas were not raised in the sea level rise simulations. Only the existing condition scenario is presented here.

AdH was executed for a "base" condition representing 2018, which is assumed here to be the "future without project" (FWOP) condition from a project planning perspective. For all simulations, outputs included the following:  

- Water surface elevations (MHHW and MLLW)  
- Salinity levels (mean)  
- Velocity

Bed elevation, water surface elevation (MHHW and MLLW), and salinity were input to the zonation functions shown in the Quantification section of this report. Figure 6.2 shows representative outputs from these functions for salinity and tidal zones as well as habitat types in the Barnegat Bay Inlet and Absecon Inlet. Notably, these habitat zones represent only AdH outputs and do not necessarily reflect regulatory definitions of ecosystems. For instance, an area identified as an estuarine, subtidal ecosystem may (or may not) currently host submerged aquatic vegetation or hard-bottom reef environments, which would imply very different outcomes from a management perspective. Likewise, an estuarine, intertidal zone may currently be developed and non-functional from an ecological perspective. However, these outputs provide broad spatial coverage not feasible to collect for the entire study area. 

<span style="color: red;">INSERT FIGURE 6.2</span>


## Environmental Data Compilation

Insert.

## Model Execution

Insert text describing the rasterization of data sets and any numerical magic.


## Summary of NYBEM Outcomes

Insert.
