# (APPENDIX) Appendices {-}

# Model Development Workshops

NYBEM has been developed through a series of workshops with USACE and non-USACE partners. This appendix provides a brief overview of workshop details.


**January 3, 2019**

*Location*: USACE Philadelphia District 

*Attendees*:  

* USACE-NAP Planning: Steve Allen, Scott Sanderson, Regina Kukola  
* USACE-NAP Engineering: Laura Bittner, Sam Weintraub, Rob Hampson, Mary Pakan  
* USACE-ERDC: Kyle McKay 

*General scope and key outcomes*:

* General overview of ecological model development  
* Preliminary conceptual model development with identification of model components  
* General categorization of conceptual model components and preliminary rendering


**March 11, 2019**

*Location*: USACE New York District 

*Attendees*:  

* USACE-NAP: Steve Allen, Rob Hampson  
* USACE-NAN: Jesse Miller, Daria Mazey, Peter Weppler, Seika Robinson, Ryan Corbett, Olivia Cackler, Bryce Wisemiller  
* USACE-NAB: Angie Sowers  
* USACE-ERDC: Kyle McKay, Todd Swannack, Darixa Hernandez-Abrams  
* U.S. Environmental Protection Agency: Barbara Spinweber (by phone) 

*General scope and key outcomes*:

* Presentation of the preliminary conceptual model from the January 2019 meeting.  
* Discussion of key ecological outcomes that need to be addressed (e.g., listed species).  
* A habitat-type modeling approach was proposed to reduce the dimensionality and complexity of the modeling problem.  Three overarching systems were identified as potential framing for model development: (1) marine / oceanside systems, (2) estuarine / bayside systems, and (3) network connectivity for the entire ecosystem.  
* For each habitat type the following issues were identified: key sub-types of habitats, construction impacts, operational impacts, direct effects (e.g., footprint effects) vs. indirect effects (e.g., changes in circulation), key intermediate processes that a model would need to capture, and key data / modeling resources.  
* A key action item was organization of a broader workshop with other agencies, entities, and project sponsors in early summer.


**June 6, 2019**

*Location*: 290 Broadway, New York 

*Attendees*:  

* USACE-NAP: Steve Allen, Laura Bittner, Rob Hampson, J.B. Smith  
* USACE-NAN: Olivia Cackler, Arun Heer, Dag Madara, Daria Mazey, Jesse Miller, Carissa Scarpa, Peter Weppler, Bryce Wisemiller  
* USACE-ERDC: Anthony Emiren, Darixa Hernandez-Abrams, Tate McAlpin, Kyle McKay  
* U.S. Fish and Wildlife Service: Kerri Dikun, Steve Mars   
* National Oceanic and Atmospheric Administration: Karen Greene  
* National Park Service: Amanda Babson, Catherine Johnson, Patricia Rafferty   
* U.S. Environmental Protection Agency: Lingaard Knutson, Mike Poetzsch, Barbara Spinweber  
* U.S. Coastal Guard: Jeff Yunker  
* U.S. Geological Survey: Stephen Terrancino  
* New Jersey Department of Environmental Protection: Kelly Davis, Vanessa Domish, Colleen Keller, Shanna Madsen, Kunal Patel, Clay Sherman, Alexis Taylor, Rob Von Briel   
* New York State Department of State: Terra Haight  
* New York State Department of Environmental Conservation: Ryan Hodgetts
* New York City Parks: Novem Auyeung, Mitchel Loring, Rebecca Swarke  
* New York City Department of Environmental Protection: Nusrat Begum, Andrew Chao, Megan Furrelle, Rupal Mehta  
* New York City Mayor's Office of Resiliency: Cherry Mui  
* Barnegat Bay Partnership: Stan Hales, Jim Vasslides  
* Hudson River Foundation: Jim Lodge  
* Stevens Institue: Philip Orton

*General scope and key outcomes*:

* Overview presentation on development approach for the New York Bight Ecological Model (NYBEM) by Dr. Kyle McKay.  
* General feedback on the scope and overall approach.  
* The workshop centered on collection of notes and ideas via a series of posters devoted to each of eight ecosystem-specific models. Morning sessions emphasized identification of key variables and processes, and afternoon sessions developed preliminary conceptual models of each ecosystem type along with qualitative responses in the form of habitat suitability curves.  
* Additional information was collection on key references, available data, existing models, and key expertise.


**November 14, 2019**

*Location*: USACE New York District 

*Attendees*:  

* USACE-NAP: Steve Allen  
* USACE-NAN: Cheryl Alkemeyer, Olivia Cackler, Jesse Miller, Alexandra Ryan, Carissa Scarpa, Danielle Tommaso, Peter Weppler, Bryce Wisemiller  
* USACE-ERDC: Kyle McKay, Darixa Hernandez-Abrams (phone)  
* U.S. Fish and Wildlife Service: Kerri Dikun (phone), Steve Papa (phone)   
* National Park Service: Patricia Rafferty   
* U.S. Environmental Protection Agency: Lingaard Knutson, Lance Caldwell, John Dawson  
* U.S. Coastal Guard: Jeff Yunker  
* U.S. Geological Survey: Liv Herdman, Chris Schubert  
* New Jersey Department of Environmental Protection: Christina Davis (phone), Kelly Davis (phone), Clay Sherman, Kelley Staffieri, Rob von Briel   
* New York State Department of Environmental Conservation: Joanna Field, Ryan Hodgetts
* New York City Parks: Georgina Cullman, Marit Larsen  
* New York City Mayor's Office of Resiliency: Adam Parris  
* Hudson River Foundation: Rob Pirani  
* HDR: Chris Coccaro

*General scope and key outcomes*:

* Overview of NYBEM development status and key open questions for discussion (Dr. Kyle McKay)  
* General discussion of key overarching issues  
* Presentation of eight ecosystem-specific conceptual models based on prior workshops  
* Attendees refined, edited, and modified ecosystem-specific models
