# USACE Model Certification Review


Model evaluation is the process for ensuring that numerical tools are scientifically defensible and transparently developed. Evaluation is often referred to as verification or validation, but it in fact includes a family of methods ranging from peer review to model testing to error checking (Schmolke et al. 2010). The USACE has established an ecological model certification process to ensure that planning models are sound and functional. These generally consist of evaluating tools relative to the three following categories: system quality, technical quality, and usability (EC 1105-2-412).

The NYBEM underwent USACE review and certification from April through August 2022. An April 2022 version of the models were reviewed by Larry Oliver (USACE New England District, "Reviewer-1"), Sean Terrill (USACE New England District, "Reviewer-2"), Richard Johansen (USACE Environmental Laboratory, "Reviewer-3"), and Kip Runyon (USACE Ecosystem Restoration Planning Center of Expertise, "Reviewer-4"). All comments follow the four-part comment structure of: (1) identify the problem, (2) describe the technical basis for the comment, (3) rate the significance or impact of the problem, and (4) recommend a mechanism for resolution. Comments and author responses are provided for transparency in review processes and long-term archival. 


**Reviewer-1**

*Comment 1.1: “The ecosystem types were adopted from a combination of two existing classifications: (Cowardin et al. 1979; USFWS 1997).” And 4.1 Habitat Zonation.* 
*I suggest future iterations the model use the USFWS (Cowardin et al.) or FGDC – CMECS classification system. The use and modification of less broadly used systems creates confusion and leads to some metrics being applied inappropriately, particularly with the use of salinity, which is very variable, as a classification factor. The model output in Section 6.3 shows what would generally be classified as estuarine habitat as marine habitat.*  
* _Basis_: This section should contain the reasons or basis for why you have the concern described above.  
* _Significance_: The outputs would be more readily understandable to a wider audience if the model used a standard classification system.  
* _Recommended Resolution_: Change to Cowardin or CMECS in any future iterations of the model.  
* _Author Response_: **Insert**.


*Comment 1.2: Documentation text - “Finally, a numerical “suitability index” was developed for each variable remaining in the sub-model, which were based on existing suitability indices, published thresholds / responses, and professional judgment.”*
*Throughout the model documentation, the text refers to the suitability index. Suitability implies that the result will answer how suitable the habitat is for a particular thing (suitability = right or appropriate for a particular person, purpose, or situation), but that’s generally not well defined in the text. The question is, “What is the cover type particularly suited for if it gets a 1.0 optimal rating?” It would be more appropriate to refer to the y axis output as a quality index as is done here: “Where Ifresh.tid is an overarching index of ecosystem quality for the freshwater, tidal zone,” but, even in that case, specifically what the index means should be clearly and completely defined. One possibility given the nature of the alternatives with the most potential significant effects – i.e., the barriers – would be to develop and call the index a resilience index. That may support the salinity, relative depth and episodic sediment deposition metrics.*  
* _Basis_: The model outputs should be defined.  
* _Significance_: High. It’s critical to know what the outputs stand for. Defining what is meant by suitability or quality would guide the model team in developing appropriate inputs.  
* _Recommended Resolution_: Define what suitability (or quality) means throughout the model documentation.  
* _Author Response_: **Insert**.


*Comment 1.3: Documentation text: 4.2 Freshwater, Tidal Zone. “Where Ifresh.tid is an overarching index of ecosystem quality for the freshwater, tidal zone, salinity is a suitability index relative to salinity, veg.cover is a suitability index relative to vegetative cover, and deposition is a suitability index relative to episodic deposition of sediment. All indices are quality metrics scaled from 0 to 1, where 0 is unsuitable and 1 is ideal.”* 
*The documentation doesn’t provide sufficient reasoning for metrics or the curve shapes. The documentation should explicitly state what the suitability index supports and provide the reasoning for the shape of the lines in the graphs. The justification for the salinity metric is that “Salinity concentration influences many chemical and physical ecological processes within the tidal freshwater ecosystem and supports euryhaline organisms.” The salinity metric graph seems to be upside down; if a marsh is above 0.5 psu 20-100% of the time it gets an SI of 1, but that would mean it’s not a tidal freshwater marsh (TFW) marsh.* 
*The SI seems to be an index of sustainability of the TFW marsh measured by salinity. It’s hard to imagine how the salinity metric will be applied to the project alternatives. Under existing conditions, all TFW marshes would get the highest rating, otherwise, they wouldn’t be TFW marshes. At some point, under the no action alternative and sea level rise, the estuarine zone would migrate upstream so the TFW marsh would become salt marsh and any upstream non-tidal freshwater marsh would become TFW marsh. That’s not necessarily a bad thing, and I don’t see a way for the model to pick up that change. With a floodgate project, the salinity will also creep up with increasingly frequent inundation under normal astronomic tides, but the marsh won’t experience as many or as high of storm tides. With the floodgate, the marsh won’t necessarily need the pulses of sediment from coastal sources (if they get up that far) because the normal tide elevations eventually won’t increase depending on the water elevation when the gates will be closed and the speed and height of SLR.* 
*It seems like it would be a pretty complex thing to figure out the percent of the time that the marsh is flooded with water greater than 0.5 psu that would have an adverse effect, especially on the low end of the graph – e.g., the difference between 5% and 15%. TFW marshes are defined based on average annual salinity.*  
* _Basis_: The documentation doesn’t seem to support the metrics sufficiently or be explicitly linked to project decision making.  
* _Significance_: High.  
* _Recommended Resolution_: I don’t think salinity is a measure of quality. It’s more a measure of what type of marsh it is or sustainability of TFW marsh. I’m not sure this model is the way to evaluate changes in salinity with the project alternatives, so I’d either provide additional reasoning and documentation or drop this metric.  
* _Author Response_: **Insert**.


*Comment 1.4: Documentation text: 4.2.2 Vegetation Cover. “For the NYBEM tidal freshwater ecosystem submodel, vegetation cover is quantified as the percentage of emergent aquatic vegetation. Emergent aquatic vegetation is a key habitat resource for species found within this ecosystem like marsh wren, and marsh wren are a key indicator species of ecosystem health because they are drawn to ideal wetland conditions. These important avian taxa are highly territorial and have a minimum habitat area of 50% emergent vegetation coverage (Gutzwiller and Anderson 1987). Marsh wrens rarely breed in marshes with less than 57% emergent vegetation (Gutzwiller and Anderson 1987). As a result, if there is less than this quantity of wetland habitat (emergent vegetation), the suitability index is presumed to be 0.”* 
*Above this section the documentation says that, “veg.cover is a suitability index relative to vegetative cover.” The documentation would be clearer if it said, “veg.cover is a suitability index that indicates [the capacity of the marsh to support marsh wrens],”or whatever its specific purpose is. Here, the text is implying that veg.cover is an index of habitat quality for marsh wrens. This puts a lot of weight on this single variable for a single species. The graph is only explicitly trying to represent one species and there are many more using this habitat type. 50% and less vegetation cover is certainly not worthless habitat and a marsh with 50% vegetative cover is optimum for some species and general abundance of species. A quick search on hemi-marsh comes up with this from Audubon: “A hemi-marsh is a type of marsh that is roughly equal parts open water and emergent vegetation or plant life. Since hemi-marsh inherently provides a diverse habitat structure, it attracts a variety of birds and other wildlife species.” The graph is not shaped correctly considering other species that might use the habitat type, but I don’t think we can draw a graph that will be useful in this situation. I think the team has to consider that what’s there on a site is good and then project future changes and determine whether they are good or not. The team could consider fully incorporating and applying several HEP models, but I’m not sure that would be worth the effort given the nature of the changes casued by the project alternatives.  I would not say that marsh wrens are a key indicator species of ecosystem health because they are drawn to ideal wetland conditions. They are drawn to ideal habitat conditions just like any other species and settle for the habitat that is available to them as long as it meets their minimum requirements.*  
* _Basis_: I don’t think there is sufficient justification for the shape of the graph line.  
* _Significance_: High.  
* _Recommended Resolution_: The team could consider fully incorporating and applying several HEP models, but I’m not sure that would be worth the effort given the nature of the changes with the project alternatives.  
* _Author Response_: **Insert**.


*Comment 1.5: 4.2.3 Episodic Sediment Deposition – “Episodic sediment deposition requires large magnitude flooding events beyond typical tidal inundation. As such, we develop a metric to assess the relative difference in depth beyond the common tidal datum of MHHW (see equation below). This relative depth metric goes to zero when there is no flooding beyond MHHW, and the metric equals one when flood magnitude is equal to MHHW.”* 
*It doesn’t seem like the documentation established the theoretical basis for the relative depth index, and there seem to be problems with the formula. The documentation needs to describe what Hmedian and Hmax are. If my check is right, if Hmedian (the elevation of a particular patch?) equals HMHHW, Hrel is 0 and the SI is 1 no matter what the Hmax is. Also, the same amount of flooding (Hmax) over a lower point on the marsh gets a lower SI than a higher point. It’s not clear why that would be. The documentation also doesn’t describe why the sediment deposition SI maxes out at a about 0.05 Hrel.*
*More importantly than the formula, the documentation should provide the rationale for why the relative depth would matter. I could see the actual depth mattering up to a point. Most marshes are pretty flat (certainly high salt marshes are relatively flat) and the hydraulic model results from whatever hydraulic model is being run for the project will indicate the depth of flooding over any patch of marsh. As the documentation says, “increased inundation in tidal freshwater marshes leads to more inorganic sediment deposition, which can assist tidal wetlands keep up with rising sea levels,” but wouldn’t it be simpler to indicate the depth of flooding necessary to maintain sufficient sediment deposition and above which detrimental effects may occur. I believe a hydraulic engineer (or hydraulic model) could estimate these thresholds based on sediment concentration and shear stress and other effects of inundation.*
*The usefulness of this metric should be considered relative to the anticipated changes in tidal hydraulics with the floodgate alternatives under the future without project conditions, project alternatives, and sea level rise scenarios and their effects on marsh sustainability.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: The usefulness of this metric should be considered relative to the anticipated changes in tidal hydraulics with the floodgate alternatives under the future without project conditions, project alternatives, and sea level rise scenarios and their effects on marsh sustainability and revise or delete the metric appropriately.  
* _Author Response_: **Insert**.


*Comment 1.6: The overall formula Ifresh.tid = (salinity+veg.cover+deposition)/3 seems to be mixing metrics that support different components of TFW marsh quality. Veg.cover seems to be based on habitat value while salinity and deposition appear to be based on sustainability. I’m not sure it makes sense to combine them into one index.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: Review and revise the formula as appropriate.  
* _Author Response_: **Insert**.


*Comment 1.7: Documentation text: 4.3 Estuarine, Intertidal Zone, 4.3.1 Edge Erosion “We assume that any increase in average velocity beyond 10% is detrimental, and that increases beyond 30% would fundamentally alter the character of a given marsh.”* 
*Some theoretical justification should be provided for this metric and statement. Edge erosion will depend on the characteristics of the marsh and the composition of the sediment, and since it’s a percentage metric, existing current speeds. The potential outcomes are that:*
*Velocity stays the same under existing conditions = 1.0 SI.*
*Velocity increases in the FWOPC without a tide gate at some point decreasing the SI.*
*Velocity may increase less with a tide gate giving a lower decrease in SI than FWOPC or an increase in the SI.*  
* _Basis_: Given the potential outcomes and the fact that this may say that having the barrier will have a better ecological outcome for this metric, it should have sufficient justification.  
* _Significance_: High.  
* _Recommended Resolution_: Provide theoretical justification for the breakpoints in the curve.  
* _Author Response_: **Insert**.


*Comment 1.8: 4.3.2 Vegetation Cover – This metric also needs more explanation other than the fact that it is adopted from a comparable suitability curve from the Wetland Value Assessment in the Gulf Coast. Ponds and pannes on salt marshes add wildlife value. I assume that’s not a consideration for this model and that it’s intended to document change as the result of changes in hydraulics with the floodgate alternatives. Any assumptions about coverage of ponds and pannes should be explained and/or reflected in the graph. The documentation should also explain how it considers any deterioration in marsh vegetation due to sea level rise.*
*It would help to indicate where the inputs for these metrics come from – i.e., for this one, the documentation should describe how the predictions about changes in percent cover are being made to be input to this model.*  
* _Basis_: Need to know the basis for the shape of the line in the graph.  
* _Significance_: Medium.  
* _Recommended Resolution_: Provide additional justification for the shape of the line and where inputs come from.  
* _Author Response_: **Insert**.


*Comment 1.9: 4.3.3 Episodic Sediment Deposition – see comments on section 4.2.3. This section describes the complex interactions of sediment transport on marshes, but settles on a simple metric without and transitional explanation.*  
* _Basis_: This section should contain the reasons or basis for why you have the concern described above.  
* _Significance_: High.  
* _Recommended Resolution_: See comments on section 4.2.3.  
* _Author Response_: **Insert**.


*Comment 1.10: 4.3.4 Development of Adjacent Upland. The documentation doesn’t provide sufficient justification for this graph. It doesn’t explain how the adjacent development affects the quality of the salt marsh. Is it about “the ability for multiple taxa to use the shoreline as migratory pathways” or is it about allowing for marsh expansion with SLR? The SLAMM Model assesses the capacity of salt marshes to migrate with SLR.* 
*“For the NYBEM, habitat suitability is modeled as a function of urban development for adjacent uplands. When the percentage of adjacent urban land uses is greater than 50%, habitat suitability in the estuarine intertidal ecosystem declines. When the development of adjacent upland reaches 100% of the estuarine intertidal ecosystem, the habitat is no longer be considered suitable.” The first sentence needs a citation or additional information to support its use. The documentation should say what it is being considered suitable for. Salt marshes within 100 meters of development may have more value in terms of environmental justice values, and as much value for aquatic and semi-aquatic organisms.* 
*This means that any patch of salt marsh or intertidal flats within 100 meters of development will be valued lower, but patches within the same marsh >100 m from the development will be valued higher. Is that practical?* 
*Also, it’s not clear how this metric would change with the various scenarios – FWOPC, structures, floodgates, and, given the nature of the areas to which the model will be applied (most likely increasing the size and height of existing structures), maybe it’s not necessary.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: Provide clearer documentation or delete the metric.  
* _Author Response_: **Insert**.


*Comment 1.11: 4.3.5 Shoreline Armoring – “For the NYBEM, the distance to the nearest armored shoreline is used to derive information about the ability for multiple taxa to use the shoreline as migratory pathways.” There’s a lot of description of shoreline armoring in the documentation, but then the model settles on interruption of migratory pathways as the reason for the graph and formula, so suitability in this case means the capacity of the shoreline to allow animals to travel between the estuarine habitat (e.g., salt marsh, mudflat, beach) and the adjacent uplands. The reasoning would then be that wildlife that can’t fly can’t migrate between the estuarine habitat and the upland habitat. Somehow that makes the quality of the marsh half to as high as habitats without armoring within the first 100 meters. The justification for the relationship needs to be provided. Since any project would have a structure at all distances (0-100 m) between the structure and the habitat, this should be a bar graph with some value for 0-100 m, rather than a line.*
*It seems like this metric would only provide useful information to assess the effects of shoreline armoring structures. Any NNBF alternative would have to consider the specific effects at the location because the NNBF feature would have to allow for migratory pathways to reduce the effect of armoring – i.e., not just be placed in front an armored shoreline. For a shoreline that already has armoring where the alternative would increase its size, it would not change the rating. For sites without armoring, it would reduce the value of the nearest 100 meters.* 
*As for the Developed Area metric, I don’t think there’s a strong case to decrease the value of a salt marsh because it’s near a structure given the project alternatives. We could use the SALM model, but I don’t think there are a lot of locations where we’re going to have salt marshes migrating inland in any significant way.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: Add documentation to support the metric, delete the metric, or consider combining it with the Developed Area metric. I recommend deleting it.  
* _Author Response_: **Insert**.


*Comment 1.12: 4.4 Estuarine, Subtidal Zone – 4.4.1 Hard Bottom Habitats - “Here, we use a historical map of oyster reef extent as a proxy for hard bottom with the assumption that hard substrate is relatively immobile and these locations would likely have higher potential for oyster reestablishment.”*
*It doesn’t seem like a good idea to use oysters, which aren’t presently occupying the site to assess the quality of the habitat. I assume there is hard bottom distributed through the estuaries where this will be applied. By applying the salinity requirements for oysters, the model will reduce the value of some hard bottom habitats for a species that’s not even there. It’s also unlikely to be affected by the project alternatives. It’s hard to imagine one of the alternatives seriously affecting hard bottom habitat in a way you could measure and consider the ultimate effects in this model.*
*How can hard bottom be a factor in evaluating hard bottom? Isn’t that a mapping factor? Interspersion is usually considered a good thing for habitat quality. Redicuing the quality rating of the habitat because it has other habitats interspersed doesn’t seem to be supported scientifically.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: I suggest dropping this metric unless the model is applied to s site with a lot of oyster habitat.  
* _Author Response_: **Insert**.


*Comment 1.13: 4.4.2 Soft Bottom Habitats*
*4.4.2.1 Submerged Aquatic Vegetation Module. Having the SAV Fine Substrate curve go down to 0.0 SI for 100% fine sediment composition doesn’t seem appropriate. The documentation should provide additional information to support this formula.*
*“New York State does not have an official standard for Secchi depth, but the state Department of Health requires 1.22 meters (4 feet) of clarity to locate a swimming beach (Lake George Association 2022). This general target aligns with ranges of observations of Secchi depth for the region (DEP 2017).” The documentation should provide justification for applying swimming beach water quality to that needed to maintain eelgrass. The whole section on light seems to need more justification. It doesn’t wrap back to a link between the final criteria and eelgrass requirements. The Ecology of Eelgrass Meadows of the Atlantic Coast: A Community Profile has a graph that appears to show optimum PAR and indicates that there are upper limits to suitable levels of PAR for eelgrass that don’t match the NYBEM graph.*
*Using vessel traffic as a proxy for human disturbance is not sufficiently justified in the documentation. There are many instances of federal channels with eelgrass adjacent to and within the channel. Also, I don’t see where the project alternatives will affect vessel traffic – except in the extreme case with sea level rise where the barrier is closed permanently. I recommend deleting this metric.*
*If the fine substrate and percent light metrics are correct and sustained, the relationship should be the lowest of substrate.sav or light, rather than adding and dividing by the number of parameters as they would be requirements.*
*4.4.2.2 Hard Clam Module – It’s unclear if the NYBEM applies the entire Hard Clam Model. The documentation should indicate whether that is the case. (I didn’t see the Thompson reference in the References section. It’s hard to envision how the team will have enough data to determine the salinity at any particular site, but if that’s possible, it’s fine.*
*This statement doesn’t appear to match the graph or the formula: “Similar to seagrass and oysters, substrate is a critical parameter for hard clam viability. Optimal substrate is shelly soft bottom. As the substrate composition increases in sand and/or mud, the substrate is less suitable for clams.” The graph says 100% sand gets the highest SI.*
*The way the soft bottom sub-model is structured, it seems like large areas of the estuaries won’t have a habitat quality rating – maybe that’s ok.*
*“As a proxy for seagrass coverage, we use the index of seagrass suitability (Iclam).” You can’t really do this. There are huge areas that look like they could support eelgrass, but don’t.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: None.  
* _Author Response_: **Insert**.


*Comment 1.14: 4.5 Marine, Intertidal Zone*
*4.5.1 Beach Slope – seabeach amaranth doesn’t grow in the marine intertidal zone. This also seems to include a model for southeast Florida. Need to indicate how alternatives would affect beach slope.*
*4.5.2 Exposure Duration – The graph doesn’t appear to be ecologically supported. The areas below the midpoint would be just as valuable as the midpoint, if not more valuable because it is likely to contain more benthic organisms even if it’s not available as long.*
*4.5.3 Upland Land Use – see previous comments on upland land use metric.*
*4.5.4 Vegetation Cover – there shouldn’t be any vegetation (other than algae and maybe extremely rare eelgrass) in the marine intertidal zone. The tern reference applies to beaches, not intertidal.*
*4.5.5 Shoreline Armoring – see previous comments.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: None.  
* _Author Response_: **Insert**.


*Comment 1.15: 4.6 Marine, Subtidal Zone - 4.6.1 Velocity, 4.6.2 Substrate, 4.6.3 Light, and 4.6.4 Vessel Density and all of 4.7 Marine, Deepwater Zone – Need additional justification.*  
* _Basis_: See above.  
* _Significance_: High.  
* _Recommended Resolution_: None.  
* _Author Response_: **Insert**.


**Reviewer-2**

*Comment 2.1: Section 3.2 - The Coastal and Marine Ecological Classification Standard (CMECS) was endorsed by the Federal Geographic Data Committee (FGDC) in 2012. As an FGDC standard, federally funded projects working with environmental data in coastal and marine settings should attempt to use CMECS as their primary classification system or attempt to crosswalk their system.*  
* _Basis_: Because USACE is a federal agency and because this project is federally funded, the NYBEM conceptual model should classify ecosystem and habitat types in accordance with CMECS to promote the standardization of habitat/ecosystem classification. Furthermore, CMECS is decades more contemporary than Cowardin et al. (1979) and USFWS (1997). However, I understand that NYBEM is, I part, built off of other models that use different classification systems, so adopting CMECS may be difficult. Furthermore, because the goal of NYBEM is not necessarily classify habitats but to assess the effects of hurricane barrier projects, a case can be made that it isn’t necessary to adopt CMECS. However, if the long-term goal is to develop this model into something that can be used in a broader capacity (i.e., in other regions for different coastal projects), then an attempt should be made to incorporate CMECS.  
* _Significance_: Medium.  
* _Recommended Resolution_: Least effort resolution is to include a statement as to why the current classification standard was chosen and a nod to why CMECS was not used as the primary classification standard, given the call for federal agencies to use CMECS.  
* _Author Response_: **Insert**.


*Comment 2.2: Section 4.2.1 - Why does the freshwater tidal zone suitability index increase with an increase in time greater than 0.5 PSU?*  
* _Basis_: If the theory is that periodic tidal influx of saltwater is beneficial to freshwater marshes through processes of sediment and nutrient deposition, but an excess of saltwater can have a harmful effect on freshwater emergent vegetation, then shouldn’t the index curve be bell-shaped (i.e., peaking at moderate salinity durations and dropping off at high and low durations)?  
* _Significance_: Medium.  
* _Recommended Resolution_: Provide a justification for the current curve or revise the salinity index to be bell-shaped if that make sense to you.  
* _Author Response_: **Insert**.


*Comment 2.3: Section 4.3.1 - I am a little skeptical about the assumption that mean current velocity and estuarine edge erosion rates are directly correlated.*  

* _Basis_: Is it possible to directly measure and model edge erosion (possibly from remote sensing such as aerial or satellite imagery)? It seems possible that in some instances (due to certain physical and biological aspects of a particular estuary) increasing velocities could potentially increase sediment accretion and decrease edge erosion (possibly by mobilizing larger quantities and larger grained sediments from outside of the estuary and depositing them into upper estuarine environments). I understand the logic and the simplicity of modeling edge erosion this way, but like Larry was saying in our review meeting, I think tidal level and wave action play important roles in this dynamic too.  
* _Significance_: Medium.  
* _Recommended Resolution_: Not necessarily recommending a change but merely suggesting taking some time to think about this index and whether there is a way to improve it within the limitations of time, budget, modeling constraints, etc.  
* _Author Response_: **Insert**.


*Comment 2.4: Section 4.3.4 - Is there a will justified reason that the estuarine intertidal land use suitability index relationship is it not linear?.*  

* _Basis_: Why would 50% urban development receive a score of 1.0, and further why would 50% urban development receive the same score as 0% development? It seems to me like the relationship should be linear with a slope of -1x, with 0% urban development receiving a score of 1.0, and 100% urban development receiving a score of 0.0. Update: After our conversation, I understand your reasoning in not wanting to penalize estuaries and marshes due to their proximity to urban development.  
* _Significance_: Low.  
* _Recommended Resolution_: Provide a justification in the text.  
* _Author Response_: **Insert**.


*Comment 2.5: Section 4.4 - “First, it was assumed that essential fish habitat would be present if oysters, SAV, and clams were present, so this variable was removed”. I’m not sure that this is a correct assumption.*  

* _Basis_: NOAA EFH is a species-specific habitat characterization. So, SAV habitat is EFH for only certain species of fish. For some species, muddy or sandy bottoms are EFH, for some cobble or ledge habitat is EFH. It also depends on the life stage of the species in question (e.g., use of SAV for nursery grounds but not for adult foraging, etc.).  
* _Significance_: Medium.  
* _Recommended Resolution_: Maybe I’m misunderstand the assumption being made but regardless I would suggest reading, incorporating, and referencing the EFH source documents for the focal taxa that the model is using as surrogates (https://www.fisheries.noaa.gov/new-england-mid-atlantic/habitat-conservation/essential-fish-habitat-efh-northeast).  
* _Author Response_: **Insert**.


*Comment 2.6: Section 4.4 - “Here, we use a historical map of oyster reef extent as a proxy for hard bottom with the assumption that hard substrate is relatively immobile and these locations would likely have higher potential for oyster reestablishment”. What about gravel, cobble, and ledge habitat?*  

* _Basis_: Are these types of geologic hard-bottom habitats present within the study areas? If so, I think they should be included. Cobble and ledge habitat have high ecological and commercial importance and should probably be considered. If a hurricane barrier project alters the amount of hard-bottom, then that would be important to know, especially because a lot of coastal NJ and NY Bight are soft-bottom habitat. For example, ledges provide habitat for kelp, benthic macroalgae, attaching sessile organisms, lobsters, and many fish species. Cobble reefs serve as a nursery for juvenile lobsters and cod. This seems important for an ecological model.  
* _Significance_: Medium.  
* _Recommended Resolution_: Incorporate geological substrate or explain that the estuarine, subtidal zone is going to be represented with focal taxa, and that hard-bottom is going to be represented by oyster cultch even though other hard-bottom habitat types exist.  
* _Author Response_: **Insert**.


*Comment 2.7: Section 4.4.2.1 - SAV: vascular plants, marine benthic macroalgae, or both?*  

* _Basis_: Both seagrasses and benthic macroalgae fall under the category of SAV but require different substrates for ideal habitat. Seagrasses require silt/sand for root expansion and nutrient uptake, while benthic macroalgae requires coarse substrates (shell reefs, shell rubble, cobbles, boulders, ledge, etc.) for attachment. In section 4.4.2.1, the authors write that “substrate is represented as the presence of soft-bottom sediments conducive for SAV growth. Based on Short et al. (2002), optimal conditions for growth were identified as non-cobble substrates with less than 70% fine sediment”. The issue is that the Short et al. (2002) paper is solely dealing with Zostera marina habitat suitability, not benthic macroalgae habitat suitability. However, many studies have found that benthic macroalgae plays an important role in photosynthesis, nursery habitat, habitat structure, etc.

I know Larry disagreed with me about whether SAV includes benthic macroalgae, but by definition, it does. Here is the definition of SAV from enclyclopedia.com : https://www.encyclopedia.com/environment/encyclopedias-almanacs-transcripts-and-maps/submerged-aquatic-vegetation. And here is the definition from NOAA: https://www.fisheries.noaa.gov/content/why-submerged-aquatic-vegetation-designated-essential-fish-habitat. NOAA mentions benthic macroalgae but only focuses on seagrasses in that article so I will acknowledge that SAV is usually seagrass-centric. But I think it’s important to also acknowledge that benthic macroalgae is an important habitat feature and provides many similar ecosystem functions as seagrasses.  
* _Significance_: Medium.  
* _Recommended Resolution_: Break out SAV into 2 groups (seagrass and benthic macroalgae) or revise the text to be specific to seagrasses and other vascular plants.  
* _Author Response_: **Insert**.


*Comment 2.8: Section 4.5 - Sea turtles shouldn’t be mentioned in the marine, intertidal zone module.*  

* _Basis_: Sea turtles typically nest in the very upper reaches of the intertidal zone or above the intertidal zone, otherwise their eggs could be smothered in water (embryos unable to respire) or washed away. But more importantly, there aren’t any sea turtles that spawn north of the Carolinas on the Atlantic Coast. Sea turtles are certainly found in the waters off of New York and New Jersey in the Summer and Fall, but not usually in the intertidal zone. Any turtles found on beaches in the intertidal zone are likely resting or stranded. The Dunkin et al. (2016) paper is focused on a study site in southern Florida, so it shouldn’t be used for NYBEM.  
* _Significance_: Medium.  
* _Recommended Resolution_: Remove sea turtle nesting from habitat suitability.  
* _Author Response_: **Insert**.


*Comment 2.9: Section 4.5 - The marine, intertidal zone module is solely focused on beach habitat.*  

* _Basis_: The use of beach slope and vegetation cover make the marine, intertidal zone module a metric of sandy beach quality. What about natural and man-made hard-bottom intertidal areas?  
* _Significance_: Medium.  
* _Recommended Resolution_: This is probably fine, because my understanding is that most of the intertidal areas of concern within the studies areas are sandy beaches. I would suggest maybe just mentioning this in the text.  
* _Author Response_: **Insert**.


*Comment 2.10: Section 4.5.4 - Vegetation cover doesn’t seem like an appropriate index for the suitability of marine, intertidal habitat.*  

* _Basis_: Beach grasses and shrubs only occur in the upper reaches of the intertidal zone, so I’m not sure if it should be used as a metric for the entirety of the marine intertidal zone? In some cases, vegetative cover is preferred by certain species at certain times, such as piping plovers, which often use beach grasses to hide their chicks after they’ve hatched. Many colonial nesting shorebirds (like terns) prefer open sandy habitat but that doesn’t mean all shorebirds do. Many shorebirds nest in beach grasses and shrubs, such as Spotted Sandpipers, Willets, and others.  
* _Significance_: Medium.  
* _Recommended Resolution_: I would suggest rethinking and updating the marine, intertidal vegetation cover index.  
* _Author Response_: **Insert**.


*Comment 2.11: Section 4.6.2 - Why does marine subtidal habitat suitability decrease linearly with percent fine substrate?*  

* _Basis_: This doesn’t entirely make ecological sense to me. Subtidal habitats with fine sediments can be optimal habitat for many important filter-feeding benthic invertebrates and thus provide important foraging habitat for demersal fish species (e.g., winter flounder, cod, etc.). From my experience collecting and processing benthic samples from a variety of sediment types, some undisturbed soft-bottom subtidal habitats can have high benthic invertebrate diversity and density. At the same time, so can hard-bottom habitats or sandy habitats, they just have different communities, not necessarily better ones.
More important than grain-size is habitat heterogeneity. Having a mix of different benthic habitats that support different communities and different life stages of benthic and demersal species is more optimal than having just one type of habitat type regardless of its perceived suitability.
See the section “Soft sediments: Unsung habitat heroes” on pg. 279 and the section “Habitat heterogeneity: Mosaics matter: on pg 281 in this paper by Kritzer et al (2016) (https://academic.oup.com/bioscience/article/66/4/274/2464081?login=true).  
* _Significance_: Medium.  
* _Recommended Resolution_: I assume that this index is probably centered around hard clam sediment suitability, but I’m not sure that hard clams can really represent the entire marine subtidal ecosystem. My suggestion is to rethink the substrate index in the marine, subtidal zone module, but at the very least to mention that it is centered on hard clam suitability.  
* _Author Response_: **Insert**.


*Comment 2.12: Section 4.6 - The Marine, Subtidal Module is essentially focused on only two taxa: hard clams and seagrasses.*  

* _Basis_: The statement: “NYBEM’s marine subtidal submodel provides a useful framework for estimating general ecosystem condition” is contradicted by the fact that it is only focused on the suitability of hard clams and seagrass. What about other benthic invertebrate species? What about coastal fish species?  
* _Significance_: High.  
* _Recommended Resolution_: The marine, subtidal zone module either needs to be expanded to include a suite of taxa or be heavily caveated in the text.  
* _Author Response_: **Insert**.


*Comment 2.13: Section 4.7 - The marine, deepwater zone should probably include metrics such as dissolved oxygen, pH, water temperature, turbidity etc..*  

* _Basis_: From an ecological perspective, I’m not totally sure that the indices used for the marine, deepwater zone are completely adequate to predict the suitability of that particular habitat type. I understand that the metrics used in the model are likely more readily available than some of the ones I’m proposing in this comment, but I think it would be beneficial to attempt to incorporate some of these metrics. For example, there should be sea surface temperature (SST) data available from NOAA. I’m not sure how you would be able to incorporate it into the model, but it would be great if that was possible. I would think that if a hurricane barrier caused less influx of cool deepwater water into an estuary, then it could cause SST in the estuary to rise which would have a negative effect on many taxa, including seagrasses. Rising SSt is also correlated with algal blooms, carbon release from the seafloor, and many other phenomena.  
* _Significance_: High.  
* _Recommended Resolution_: If possible, expand the Marine, Deepwater Zone module.  
* _Author Response_: **Insert**.


*Comment 2.14: I think it would be a good idea to reach out to some estuarine and coastal marine ecologists from academia, non-profit organizations, state, and federal agencies, etc. to get some input on what the most appropriate focal/ surrogate taxa are for each sub-model and then building the sub models off of those particular taxa.*  

* _Basis_: Often while reading through the NYBEM documentation, I would think to myself “suitable habitat for what taxa”? The idea of suitable habitat is such a species-specific concept (e.g., suitable subtidal habitat for lobster or blue crab is vastly different than subtidal habitat for striped bass or bluefish). I’m not saying that seagrass and hard clams are not appropriate focal taxa but I’m not sure if they are appropriate focal taxa for the entirety of NYBEM. I think that sub models such as the marine, subtidal zone and the marine, deepwater zone could be improved by adopting different focal taxa and building the indices off of them. Maybe federally endangered taxa are a good place to start, seeing as this model is being built to forecast the effects of federal projects?  
* _Significance_: High.  
* _Recommended Resolution_: I’m not familiar enough with the ecology of the NY Bight or NJ estuaries to suggest any taxa, but I can envision a NYBEM where each sub model is built off of say 1-3 focal taxa, which are clearly specified in the text, from which the indices are clearly related. I think this approach would be straight forward and efficient and would potentially alleviate a lot of the types of comments I made above.  
* _Author Response_: **Insert**.


**Reviewer-3**

*Comment 3.1: All functions within the `nybem` R package should have proper documentation, sample data, and provide a basic example of its functionality.*  
* _Basis_: This is a basic requirement for publishing open source/public R packages to ensure the package and its functions are comprehendible and usable to all users. Additionally, this can help users navigate their own technical challenges by providing a working example with appropriate syntax.  
* _Significance_: High.  
* _Recommended Resolution_: Create a vignette with working example(s) for each major `nybem` function, using sample data embedded into the package itself. For these basic examples, users should not be expected to pull data from other sources (R packages, repos, websites, etc.).  
* _Author Response_: **Concur**. All functions are written to include standard format and help documentation. Test data and a testing record are included within the `tests` folder of the package.


*Comment 3.2: `SIcalc` code and documentation.*  

- _Basis_: The “approx.” function used in the SIcalc function seems to appropriately interpolate between the SI break points, but this might be initially difficult for users to determine since it is presented quite differently in the documentation vs. the R package/vignette.
- _Significance_: High.  
- _Recommended Resolution_: Be explicit in documentation on which set of input variables are defined for each model. For example, nybem_submodels$NYBEM.mar.int documentation shows that “exp dur” with a range of 0-1 is expected, but “trel”, with a range of 0-100 used. This is not the same documentation as land.use which has urban.per as input. Just need to be clear and constant about how to interpret these models and what are actually user inputs.  
- _Author Response_: **Concur**. Documentation was revised to reflect the correct variable naming as indicated.


*Comment 3.3: Calling variables in `SIcalc`.*  

- _Basis_: The `nybem` submodels require users to specify the input variables in the right order. It might be more appropriate for the function to look for the names of each variable not the index location. Example below:

```{r echo=TRUE}
#obs_1 <- list(beach.slope, exp.dur, land.use, shoreline, veg.cover) 
#SIcalc(SI = nybem_submodels$NYBEM.mar.int, input_proj = obs_1)

#!=

#obs_1 <- list(beach.slope, exp.dur, land.use, veg.cover, shoreline)
#SIcalc(SI = nybem_submodels$NYBEM.mar.int, input_proj = obs_1)
```

- _Significance_: High.  
- _Recommended Resolution_: This might be a bit picky but I really think it is important to choice between a linear model look up table or interpolating between breakpoints. Just be clear and consistent throughout all documentation.  
- _Author Response_: **Non-concur**. The reviewer makes an excellent point about calling variables directly. However, the `nybem` code was written to mirror variable structure from an existing package (`ecorest`). Variable calls were double-checked to ensure consistency in look-up referencing.


**Reviewer-4**

*Comment 4.1: Given the potential phased approach for these studies and the model, we need to make sure we have a good method for tracking the model and model documentation version(s).*  

- _Basis_: We need to avoid a situation where potential model users, reviewers, etc. are unclear on what version of the model is being used and whether or not that version is certified.  
- _Significance_: Medium – potential inadvertent use of uncertified model.  
- _Recommended Resolution_: As discussed during our mid-review webex, recommend clear communication in the model documentation of the model version, certification status, any changes made since certification, etc. Also agree with the recommendation of using the CRAN website for version tracking of the R software package(s).  
- _Author Response_: **Concur**. The certified version of the model will be uploaded to [CRAN}(https://cran.r-project.org/web/packages/available_packages_by_name.html), and the associated documentation will be peer-reviewed and published as an ERDC technical report. The model code and documents will be clearly labeled as version 1.0.0, and any subsequent revisions will be identified from new version numbering. Web-based model documents will be labeled and linked accordingly.


*Comment 4.2: Section 4.4.2.2 indicates that optimal clam substrate is shelly soft bottom and as the substrate composition increases in sand and/or mud, the substrate is less suitable for clams. This is contradicted by the HSI curve which indicates increasing suitability as sand composition increases.*  

- _Basis_: Contradiction in description of metric vs. HSI curve and formulas.  
- _Significance_: Low.  
- _Recommended Resolution_: Recommend either modifying text to comport with HSI curve and formulas or vice versa.  
- _Author Response_: **Concur**. Text and figures were aligned.


# References
